version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type : single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.9.2
    ports:
      - "5601:5601"